### ISSUE TITLE
Ignore tests

### ISSUE THREAD

**Issue by RazrFalcon** [anderejd/cargo-geiger#3]
Currently, the test code is also included, which is misleading.

For example, the `float-cmp` crate has only [two unsafe expressions](https://github.com/mikedilger/float-cmp/blob/6ecb629f58d5ccf5f88b999daa5ceb73a26dafd6/src/ulps.rs#L36..L37), but 32 are reported.

**Comment by anderejd** [comment]
Good find! Thank you.

**Comment by anderejd** [comment]
Question: Should there be a command line flag to include tests but keep it off by default?

**Comment by RazrFalcon** [comment]
Unsafe in tests is irrelative to the crate itself. They will not be included into the parent crate. So I don't see a point in including them even as an option.

**Comment by anderejd** [comment]
Sounds reasonable to me 👍

**Comment by anderejd** [comment]
A similar issue: https://github.com/anderejd/cargo-geiger/issues/12

**Comment by anderejd** [comment]
Related to: https://github.com/anderejd/cargo-geiger/issues/14

**Comment by anderejd** [comment]
Since #26 the counts for `float-cmp` seems correct to me.

Since this commit:
https://github.com/anderejd/cargo-geiger/commit/9fa3534e01211552432e7b904b8baa16d1728350
there's a new flag `--include-tests`. Without it `float-cmp` reports 8/8 unsafe expressions which seems correct, it has four transmutes each with a dereference expression inside. With `--include-tests` the count is 20/20 unsafe expressions.

**Comment by anderejd** [comment]
Commit: https://github.com/anderejd/cargo-geiger/commit/cdccce62df2649b94dae0cb5e1272079fade866e adds default ignore filter for `#[cfg(test)]` modules.

I think this issue can be closed now. Feel free to reopen if the solution is not good enough.
