### ISSUE TITLE
Scanning message with `-q true`

### ISSUE THREAD

**Issue by Proximyst** [anderejd/cargo-geiger#61]
When calling with `cargo geiger -q true`, `Scanning...` then `Scanning...Done` is printed to stdout, which deviates from the parameter's description. The metric format and symbols descriptions are also shown which I'm unsure if should be the case.

https://proletariat-dictatorship.is-serious.business/6wYrtmr.png

**Comment by anderejd** [comment]
Thank you for the report!

This is due to me copy-pasting too much of the cargo-tree and cargo-osha projects when putting together the first version of cargo-geiger.

It seems that I forgot to properly review and adjust the command line flags, would you like to do it? 🙂 There might be quite a few more of them that should be either removed or fixed.

Related to #60

**Comment by anderejd** [comment]
Fixed by: #66
