### ISSUE TITLE
No support for git dependencies?

### ISSUE THREAD

**Issue by RazrFalcon** [anderejd/cargo-geiger#62]
Trying to check [this](https://github.com/RazrFalcon/resvg/tree/d0bfbacef7212efce4421ec532b0d98d91820bf9) resvg commit:

```
...

    Checking resvg v0.7.0 (../Projects/rust/resvg)
    Finished dev [unoptimized + debuginfo] target(s) in 18.21s
    Scanning...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorMessage { msg: "couldn\'t find sourcefor `pico-args v0.1.0 (https://github.com/RazrFalcon/pico-args?rev=f9e8b51#f9e8b51e)`" }

failed to download `pico-args v0.1.0 (https://github.com/RazrFalcon/pico-args?rev=f9e8b51#f9e8b51e)`', src/libcoreresult.rs:997:5
```

**Comment by anderejd** [comment]
Thanks for the report! This is definitely unexpected and is likely a bug in cargo-geiger. It seems like I have overlooked something in the cargo API related to downloads or source code locations. I'll try to find some time to look into this in a week or two.

**Comment by jakubadamw** [comment]
No, this is not a problem with Git dependencies. That package is structured as a workspace with a top-level package (i.e. a workspace that has a number of member packages *and* a top-level package) and that's the defining condition of the problem, it's just so happened that the first offending dependency triggering it happened to be a Git dependency (and that's due to Cargo processing dependencies in that order, with Git-sourced ones first).

So in a workspace like this `cargo geiger` has been, I think, designed to only look at the top-level package. For one, it only prints out a single dependency tree with statistics. But for the actual search through the code it picks the dependencies of *all* member packages in the workspace, which breaks when it actually tries to retrieve the source, which it wouldn't have for dependencies that had not been `cargo check`ed before.

I've got a fix for this, I'll submit a PR.

**Comment by pinkforest** [comment]
@jakubadamw funny thing - I went down the rabbithole to trace related issue down here https://github.com/rust-secure-code/cargo-geiger/issues/83#issuecomment-1006431479

It was essentially cargo / url issue related to Git which postdates the changes in cargo and url::Url that would have broken this again.
